dubbo:
  # 配置服务信息
  application:
    id: order-service
    name: order-service
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://127.0.0.1:8848
  # 设置超时时间
  consumer:
    timeout: 6000
  protocol:
    name: dubbo
    port: 20881
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true